In [1]:
from tasks.VSTtask import VSTtask
from agents.LLMagent import LLMagent
from manager.TaskManager import TaskManager

In [10]:
YOUR_ANTHROPIC_API_KEY=""
YOUR_OPENAI_API_KEY = ""

# To use OpenAI:
#agent = LLMagent(model_name="gpt-4o-mini", openai_api_key=YOUR_OPENAI_API_KEY)

# To use Anthropic:
#agent = LLMagent(model_name="claude-3-5-sonnet-latest", anthropic_api_key=YOUR_ANTHROPIC_API_KEY)

# To use a local model:
#agent = LLMagent(model_name="Deepseek_R1_7B_Qwen", use_unsloth=True, device_map="cuda:0")


In [5]:
import numpy as np
import pickle
import time

start_time = time.time()

# Benchmark plot
agents = ["Deepseek_R1_1B_Qwen", "Deepseek_R1_7B_Qwen", "Deepseek_R1_8B_Llama", 
          "Qwen_1B", "Qwen_3B", "Qwen_7B", "Qwen_1B_Instruct", "Qwen_3B_Instruct", 
          "Qwen_7B_Instruct", "Centaur_8B"]

rounds = [5, 10, 50, 100]
quadrants = [2, 4]

results = np.zeros((10, 4, 2, 5))
for agent, a in zip(agents, range(10)):
    pipe = LLMagent(model_name=agent, use_unsloth=True, device_map="cuda:0")
    for rnd, r in zip(rounds, range(4)):
        for quadrant, q in zip(quadrants, range(2)):
            for i in range(5):
                manager = TaskManager(n_simulations=10, n_rounds=rnd, num_quadrants=quadrant, num_cues=1, pipe=pipe, verbose=False)
                metrics = manager.run_simulations()
                results[a, r, q, i] = metrics['success_rate']

with open("results.pkl", "wb") as f:
    pickle.dump(results, f)

elapsed_time = time.time() - start_time
print(f"Total elapsed time: {elapsed_time:.2f} seconds")


Using unsloth with GPU
==((====))==  Unsloth 2025.2.5: Fast Qwen2 patching. Transformers: 4.48.3.
   \\   /|    GPU: NVIDIA GeForce RTX 4090. Max memory: 23.621 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post2. FA2 = False]
 "-____-"     Free Apache license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!


Device set to use cuda:0
100%|███████████████████████████████████████████| 10/10 [00:35<00:00,  3.54s/it]


Using unsloth with GPU
==((====))==  Unsloth 2025.2.5: Fast Qwen2 patching. Transformers: 4.48.3.
   \\   /|    GPU: NVIDIA GeForce RTX 4090. Max memory: 23.621 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post2. FA2 = False]
 "-____-"     Free Apache license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Device set to use cuda:0
100%|███████████████████████████████████████████| 10/10 [02:10<00:00, 13.00s/it]


Using unsloth with GPU
==((====))==  Unsloth 2025.2.5: Fast Llama patching. Transformers: 4.48.3.
   \\   /|    GPU: NVIDIA GeForce RTX 4090. Max memory: 23.621 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post2. FA2 = False]
 "-____-"     Free Apache license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!


Device set to use cuda:0
100%|███████████████████████████████████████████| 10/10 [02:13<00:00, 13.37s/it]


Using unsloth with GPU
==((====))==  Unsloth 2025.2.5: Fast Qwen2 patching. Transformers: 4.48.3.
   \\   /|    GPU: NVIDIA GeForce RTX 4090. Max memory: 23.621 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post2. FA2 = False]
 "-____-"     Free Apache license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!


Device set to use cuda:0
100%|███████████████████████████████████████████| 10/10 [00:35<00:00,  3.58s/it]


Using unsloth with GPU
==((====))==  Unsloth 2025.2.5: Fast Qwen2 patching. Transformers: 4.48.3.
   \\   /|    GPU: NVIDIA GeForce RTX 4090. Max memory: 23.621 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post2. FA2 = False]
 "-____-"     Free Apache license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!


Device set to use cuda:0
100%|███████████████████████████████████████████| 10/10 [01:02<00:00,  6.29s/it]


Using unsloth with GPU
==((====))==  Unsloth 2025.2.5: Fast Qwen2 patching. Transformers: 4.48.3.
   \\   /|    GPU: NVIDIA GeForce RTX 4090. Max memory: 23.621 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post2. FA2 = False]
 "-____-"     Free Apache license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Device set to use cuda:0
100%|███████████████████████████████████████████| 10/10 [02:08<00:00, 12.88s/it]


Using unsloth with GPU
==((====))==  Unsloth 2025.2.5: Fast Qwen2 patching. Transformers: 4.48.3.
   \\   /|    GPU: NVIDIA GeForce RTX 4090. Max memory: 23.621 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post2. FA2 = False]
 "-____-"     Free Apache license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!


Device set to use cuda:0
100%|███████████████████████████████████████████| 10/10 [00:37<00:00,  3.74s/it]


Using unsloth with GPU
==((====))==  Unsloth 2025.2.5: Fast Qwen2 patching. Transformers: 4.48.3.
   \\   /|    GPU: NVIDIA GeForce RTX 4090. Max memory: 23.621 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post2. FA2 = False]
 "-____-"     Free Apache license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!


Device set to use cuda:0
100%|███████████████████████████████████████████| 10/10 [01:02<00:00,  6.25s/it]


Using unsloth with GPU
==((====))==  Unsloth 2025.2.5: Fast Qwen2 patching. Transformers: 4.48.3.
   \\   /|    GPU: NVIDIA GeForce RTX 4090. Max memory: 23.621 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post2. FA2 = False]
 "-____-"     Free Apache license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Device set to use cuda:0
100%|███████████████████████████████████████████| 10/10 [02:08<00:00, 12.88s/it]


Using unsloth with GPU
==((====))==  Unsloth 2025.2.5: Fast Llama patching. Transformers: 4.48.3.
   \\   /|    GPU: NVIDIA GeForce RTX 4090. Max memory: 23.621 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post2. FA2 = False]
 "-____-"     Free Apache license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!


Device set to use cuda:0
The model 'PeftModelForCausalLM' is not supported for text-generation. Supported models are ['AriaTextForCausalLM', 'BambaForCausalLM', 'BartForCausalLM', 'BertLMHeadModel', 'BertGenerationDecoder', 'BigBirdForCausalLM', 'BigBirdPegasusForCausalLM', 'BioGptForCausalLM', 'BlenderbotForCausalLM', 'BlenderbotSmallForCausalLM', 'BloomForCausalLM', 'CamembertForCausalLM', 'LlamaForCausalLM', 'CodeGenForCausalLM', 'CohereForCausalLM', 'Cohere2ForCausalLM', 'CpmAntForCausalLM', 'CTRLLMHeadModel', 'Data2VecTextForCausalLM', 'DbrxForCausalLM', 'DiffLlamaForCausalLM', 'ElectraForCausalLM', 'Emu3ForCausalLM', 'ErnieForCausalLM', 'FalconForCausalLM', 'FalconMambaForCausalLM', 'FuyuForCausalLM', 'GemmaForCausalLM', 'Gemma2ForCausalLM', 'GitForCausalLM', 'GlmForCausalLM', 'GPT2LMHeadModel', 'GPT2LMHeadModel', 'GPTBigCodeForCausalLM', 'GPTNeoForCausalLM', 'GPTNeoXForCausalLM', 'GPTNeoXJapaneseForCausalLM', 'GPTJForCausalLM', 'GraniteForCausalLM', 'GraniteMoeForCausalLM', 'Jam

Total elapsed time: 12222.83 seconds


In [8]:
print(results)

[[[[0.  0.  0.  0.1 0. ]
   [0.  0.  0.  0.  0. ]]

  [[0.  0.  0.  0.  0. ]
   [0.  0.  0.1 0.  0. ]]

  [[0.  0.  0.  0.  0. ]
   [0.  0.  0.  0.  0. ]]

  [[0.  0.  0.  0.  0. ]
   [0.  0.  0.  0.  0. ]]]


 [[[0.  0.1 0.  0.1 0. ]
   [0.  0.  0.  0.  0. ]]

  [[0.  0.3 0.  0.  0. ]
   [0.  0.1 0.  0.  0.1]]

  [[0.1 0.  0.1 0.  0. ]
   [0.  0.  0.  0.  0. ]]

  [[0.  0.  0.1 0.1 0. ]
   [0.  0.  0.  0.  0. ]]]


 [[[0.  0.  0.1 0.  0. ]
   [0.  0.  0.  0.  0. ]]

  [[0.  0.  0.  0.  0. ]
   [0.  0.  0.  0.  0. ]]

  [[0.  0.  0.  0.  0. ]
   [0.  0.  0.  0.  0. ]]

  [[0.  0.  0.  0.  0. ]
   [0.  0.  0.  0.  0. ]]]


 [[[0.1 0.1 0.  0.  0. ]
   [0.1 0.  0.  0.  0. ]]

  [[0.2 0.  0.1 0.  0.1]
   [0.1 0.  0.  0.  0. ]]

  [[0.  0.  0.  0.  0. ]
   [0.  0.  0.1 0.1 0.1]]

  [[0.1 0.  0.  0.  0. ]
   [0.  0.  0.1 0.  0. ]]]


 [[[0.  0.  0.  0.1 0.2]
   [0.  0.  0.1 0.  0.2]]

  [[0.1 0.  0.2 0.2 0.1]
   [0.1 0.  0.1 0.1 0. ]]

  [[0.  0.  0.1 0.1 0. ]
   [0.  0.  0.  0.1 0. ]]

  [[

In [2]:
import numpy as np
import pickle
import time

start_time = time.time()

# Benchmark plot
#agents = ["gpt-4o", "gpt-4o-mini", "o1-mini"]

rounds = [5, 10, 50, 100]
quadrants = [2, 4]

results_openai2 = np.zeros((2, 4, 2, 5))
for agent, a in zip(agents, range(2)):
    pipe = LLMagent(model_name=agent, openai_api_key=YOUR_OPENAI_API_KEY)
    for rnd, r in zip(rounds, range(4)):
        for quadrant, q in zip(quadrants, range(2)):
            for i in range(5):
                manager = TaskManager(n_simulations=10, n_rounds=rnd, num_quadrants=quadrant, num_cues=1, pipe=pipe, verbose=False)
                metrics = manager.run_simulations()
                results_openai2[a, r, q, i] = metrics['success_rate']

with open("results_openai2.pkl", "wb") as f:
    pickle.dump(results_openai2, f)

elapsed_time = time.time() - start_time
print(f"Total elapsed time: {elapsed_time:.2f} seconds")


Using OpenAI API for GPT model


100%|██████████████████████████████████████████| 10/10 [24:13<00:00, 145.30s/it]


Using OpenAI API for GPT model


  0%|                                                    | 0/10 [00:00<?, ?it/s]


NotFoundError: Error code: 404 - {'error': {'message': 'The model `o3-mini` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}